version: "3.8"
services:

  data_processing: 
    build: ./processing
    command : python processing/app.py 
    ports : 5002:5002 configs:
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - .:/processing 
    links: 
      - db 
    depends_on: 
      - db 
  app:
    build: ./app
    command: python app/app.py
    ports:
      - 5001:5001
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/app
    links: 
      - db
    depends_on: 
      - db 
      - data_processing
  db: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - pg_db:/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pg_db:
    driver: local